### ISSUE TITLE
Cache file loading

### ISSUE THREAD

**Issue by saibotk** [piegamesde/VoicePi#1]
```PS D:\Downloads\voicepi-0.2.0-bin\voicepi-0.2.0> java -jar voicepi-0.2.0.jar
18-03-21 11:31:28:107 INFO  VoicePi [144] - Reloading all modules
18-03-21 11:31:28:133 INFO  Configuration [72] - Loading configuration from file D:\Downloads\voicepi-0.2.0-bin\voicepi-0.2.0\config.json
18-03-21 11:31:28:143 DEBUG VoicePi [173] - Loaded settings: Settings [onStart=de.piegames.voicepi.action.SayTextAction@691a7f8f, onExit=de.piegames.voicepi.action.SayTextAction@50a7bc6e, onActivation=de.piegames.voicepi.action.PlaySoundAction@161b062a, onTimeout=de.piegames.voicepi.action.PlaySoundAction@17c1bced, onReload=de.piegames.voicepi.action.Action$DoNothingAction@2d9d4f9d, onWrongCommand=de.piegames.voicepi.action.PlaySoundAction@4034c28c, timeout=30, activationCommands=[RASPBERRY]]
18-03-21 11:31:28:151 DEBUG VoiceState [42] - Setting activation commands to [RASPBERRY]
18-03-21 11:31:28:158 DEBUG ApplicationModule [22] - Commands to exit the application: [EXIT]
18-03-21 11:31:28:159 DEBUG ApplicationModule [23] - Commands to reload the modules of the application: [RELOAD]
18-03-21 11:31:28:170 DEBUG VoicePi [195] - All registered commands:
RELOAD
TEST
RASPBERRY
EXIT
18-03-21 11:31:28:172 DEBUG CommandsCache [30] - Caching command data at D:\Downloads\voicepi-0.2.0-bin\voicepi-0.2.0\cache.json
18-03-21 11:31:28:172 DEBUG CommandsCache [35] - Loading cache from file
Exception in thread "main" Property exception component:'simpleNGramModel' property:'location' - Bad URL C:\Users\Tobias\AppData\Local\Temp\cached9024331397677580668.lmunknown protocol: c
edu.cmu.sphinx.util.props.InternalConfigurationException: Bad URL C:\Users\Tobias\AppData\Local\Temp\cached9024331397677580668.lmunknown protocol: c
        at edu.cmu.sphinx.util.props.ConfigurationManagerUtils.getResource(ConfigurationManagerUtils.java:472)
        at edu.cmu.sphinx.linguist.language.ngram.SimpleNGramModel.newProperties(SimpleNGramModel.java:99)
        at edu.cmu.sphinx.util.props.PropertySheet.getOwner(PropertySheet.java:518)
        at edu.cmu.sphinx.util.props.PropertySheet.getComponent(PropertySheet.java:296)
        at edu.cmu.sphinx.linguist.lextree.LexTreeLinguist.newProperties(LexTreeLinguist.java:305)
        at edu.cmu.sphinx.util.props.PropertySheet.getOwner(PropertySheet.java:518)
        at edu.cmu.sphinx.util.props.PropertySheet.getComponent(PropertySheet.java:296)
        at edu.cmu.sphinx.decoder.search.WordPruningBreadthFirstSearchManager.newProperties(WordPruningBreadthFirstSearchManager.java:211)
        at edu.cmu.sphinx.decoder.search.WordPruningBreadthFirstLookaheadSearchManager.newProperties(WordPruningBreadthFirstLookaheadSearchManager.java:156)
        at edu.cmu.sphinx.util.props.PropertySheet.getOwner(PropertySheet.java:518)
        at edu.cmu.sphinx.util.props.PropertySheet.getComponent(PropertySheet.java:296)
        at edu.cmu.sphinx.decoder.AbstractDecoder.newProperties(AbstractDecoder.java:81)
        at edu.cmu.sphinx.decoder.Decoder.newProperties(Decoder.java:36)
        at edu.cmu.sphinx.util.props.PropertySheet.getOwner(PropertySheet.java:518)
        at edu.cmu.sphinx.util.props.PropertySheet.getComponent(PropertySheet.java:296)
        at edu.cmu.sphinx.recognizer.Recognizer.newProperties(Recognizer.java:86)
        at edu.cmu.sphinx.util.props.PropertySheet.getOwner(PropertySheet.java:518)
        at edu.cmu.sphinx.util.props.ConfigurationManager.lookup(ConfigurationManager.java:163)
        at edu.cmu.sphinx.api.Context.<init>(Context.java:73)
        at edu.cmu.sphinx.api.Context.<init>(Context.java:45)
        at edu.cmu.sphinx.api.AbstractSpeechRecognizer.<init>(AbstractSpeechRecognizer.java:44)
        at edu.cmu.sphinx.api.LiveSpeechRecognizer.<init>(LiveSpeechRecognizer.java:34)
        at de.piegames.voicepi.stt.SphinxRecognizer.load(SphinxRecognizer.java:110)
        at de.piegames.voicepi.VoicePi.reload(VoicePi.java:207)
        at de.piegames.voicepi.VoicePi.main(VoicePi.java:258)
Caused by: java.net.MalformedURLException: unknown protocol: c
        at java.net.URL.<init>(Unknown Source)
        at java.net.URL.<init>(Unknown Source)
        at java.net.URL.<init>(Unknown Source)
        at edu.cmu.sphinx.util.props.ConfigurationManagerUtils.resourceToURL(ConfigurationManagerUtils.java:488)
        at edu.cmu.sphinx.util.props.ConfigurationManagerUtils.getResource(ConfigurationManagerUtils.java:465)
        ... 24 more```

**Comment by saibotk** [comment]
Fixed with dcddbf0
